<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Ecobin Memory Game</title>
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
<!-- FontAwesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

<style>
body {
  font-family: 'Comic Sans MS', cursive, sans-serif;
  background: linear-gradient(135deg,#ffe6e6,#fff0f5);
  padding-top: 70px;
  display: flex;
  flex-direction: column;
  align-items: center;
}


/* Navbar */
.navbar {
  background-color:#c30010;
}
.navbar-brand, .navbar-nav .nav-link{
  color:#fff !important;
}
.navbar-nav .nav-link:hover{
  color:#ffd6d9 !important;
}
/* Title */
.game-title{
  text-align:center;
  margin:30px 0;
  animation: bounce 2s infinite;
}
.game-title h2{
  font-size:42px;
  color:#ff1744;
  font-weight:bold;
  text-shadow: 2px 2px #fff;
}
.game-title p{
  font-size:18px;
  color:#555;
}

/* Game Container */
.game-container{
  display: grid;
  grid-template-columns: repeat(4, 120px);
  grid-gap: 15px;
  justify-content: center;
  margin-bottom: 20px;
}

/* Cards */
.card{
  width: 120px;
  height: 120px;
  background: linear-gradient(135deg,#fff0f0,#ffd6d6);
  display: flex;
  justify-content: center;
  align-items: center;
  font-size: 40px;
  color: #de0a26;
  cursor: pointer;
  border-radius: 12px;
  box-shadow: 0 4px 10px rgba(0,0,0,0.2);
  transition: transform 0.3s, background 0.3s;
}
.card:hover{
  transform: scale(1.1);
  box-shadow:0 8px 20px rgba(255,23,68,0.5);
}
.card.flipped{
  background:#ff1744;
  color:#fff;
  cursor: default;
}

/* Timer */
.timer{
  font-size:24px;
  font-weight:bold;
  text-align:center;
  color:#ff1744;
  margin-bottom:20px;
  animation: pulse 1s infinite;
}

/* Start Button */
.btn-play{
  display:block;
  margin:20px auto;
  background: linear-gradient(to right,#ff1744,#ff5252);
  color:#fff;
  padding:12px 28px;
  font-size:20px;
  font-weight:bold;
  border-radius:15px;
  text-decoration:none;
  transition: transform 0.2s, box-shadow 0.2s;
}
.btn-play:hover{
  transform: scale(1.1) rotate(-2deg);
  box-shadow:0 0 25px #ff1744;
}

/* Back Button */
.btn-back{
  display:block;
  margin:20px auto;
  background:#333;
  color:#fff;
  padding:12px 30px;
  font-size:16px;
  font-weight:bold;
  border-radius:10px;
  text-decoration:none;
  transition: transform 0.2s, box-shadow 0.2s;
}
.btn-back:hover{
  transform: scale(1.05);
  background:#555;
  box-shadow:0 0 15px #333;
}

/* Animations */
@keyframes bounce {
  0%, 100% { transform: translateY(0);}
  50% { transform: translateY(-10px);}
}
@keyframes pulse {
  0%, 100% { transform: scale(1);}
  50% { transform: scale(1.1);}
}
</style>
</head>
<body>



<!-- Title -->
<div class="game-title">
  <h2>Memory Matching Game</h2>
  <p>Match all pairs of e-waste items before time runs out! (45 sec)</p>
</div>

<!-- Timer -->
<div class="timer" id="timer">Time Left: 00:45</div>

<!-- Game Container -->
<div class="game-container" id="gameContainer">
  <!-- Cards generated by JS -->
</div>

<!-- Start / Back -->
<a href="#" id="start-btn" class="btn-play">Start Game</a>
<a href="game.php" class="btn-back"><i class="fas fa-arrow-left"></i> Back to Games</a>

<script>
const gameContainer = document.getElementById('gameContainer');
const startBtn = document.getElementById('start-btn');
const timerDisplay = document.getElementById('timer');

// E-Waste icons (8 pairs)
const icons = ["<i class='fas fa-mobile-alt'></i>",
               "<i class='fas fa-laptop'></i>",
               "<i class='fas fa-plug'></i>",
               "<i class='fas fa-tv'></i>",
               "<i class='fas fa-battery-three-quarters'></i>",
               "<i class='fas fa-keyboard'></i>",
               "<i class='fas fa-headphones'></i>",
               "<i class='fas fa-camera'></i>"];

let firstCard=null, secondCard=null, lockBoard=false, matchedPairs=0;
let timer, timeLeft=45;

// Shuffle array
function shuffle(array){return array.sort(()=>0.5-Math.random());}

// Start game
startBtn.addEventListener('click', ()=>{
  startBtn.style.display='none';
  matchedPairs=0;
  gameContainer.innerHTML='';
  let cardsArray=[...icons,...icons];
  shuffle(cardsArray);
  cardsArray.forEach(icon=>{
    const card=document.createElement('div');
    card.classList.add('card');
    card.innerHTML=icon;
    card.dataset.icon=icon;
    card.addEventListener('click', flipCard);
    gameContainer.appendChild(card);
  });
  startTimer();
});

// Flip card
function flipCard(){
  if(lockBoard || this.classList.contains('flipped')) return;
  this.classList.add('flipped');
  if(!firstCard){firstCard=this; return;}
  secondCard=this;
  checkMatch();
}

function checkMatch(){
  if(firstCard.dataset.icon===secondCard.dataset.icon){
    matchedPairs++;
    firstCard.removeEventListener('click', flipCard);
    secondCard.removeEventListener('click', flipCard);
    resetBoard();
    if(matchedPairs===icons.length){
      clearInterval(timer);
      alert('🎉 You matched all items!');
      startBtn.style.display='block';
    }
  } else {
    lockBoard=true;
    setTimeout(()=>{
      firstCard.classList.remove('flipped');
      secondCard.classList.remove('flipped');
      resetBoard();
    },1000);
  }
}

function resetBoard(){
  [firstCard,secondCard]=[null,null];
  lockBoard=false;
}

// Timer
function startTimer(){
  timeLeft=45;
  timerDisplay.innerText=`Time Left: 00:${timeLeft<10?'0'+timeLeft:timeLeft}`;
  timer=setInterval(()=>{
    timeLeft--;
    timerDisplay.innerText=`Time Left: 00:${timeLeft<10?'0'+timeLeft:timeLeft}`;
    if(timeLeft<=0){
      clearInterval(timer);
      alert('⏰ Time over! Try again.');
      startBtn.style.display='block';
    }
  },1000);
}
</script>

<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
